channels:
- conda-forge
- defaults
dependencies:
- conda-forge::blas=1.1=openblas
- conda-forge::cairo=1.12.18=8
- conda-forge::cloudpickle=0.2.1=py27_2
- conda-forge::cycler=0.10.0=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::fontconfig=2.11.1=3
- conda-forge::freetype=2.6.3=1
- conda-forge::funcsigs=1.0.2=py27_0
- conda-forge::functools32=3.2.3.2=py27_1
- conda-forge::gettext=0.19.7=1
- conda-forge::glib=2.48.0=4
- conda-forge::harfbuzz=1.0.6=0
- conda-forge::icu=56.1=4
- conda-forge::jpeg=9b=0
- conda-forge::libffi=3.2.1=2
- conda-forge::libiconv=1.14=3
- conda-forge::libpng=1.6.24=0
- conda-forge::libtiff=4.0.6=6
- conda-forge::libxml2=2.9.4=2
- conda-forge::matplotlib=1.5.3=np111py27_2
- conda-forge::numpy=1.11.2=py27_blas_openblas_200
- conda-forge::openblas=0.2.18=5
- conda-forge::pandas=0.19.0=np111py27_0
- conda-forge::pango=1.40.1=0
- conda-forge::pcre=8.38=1
- conda-forge::pixman=0.32.6=0
- conda-forge::pyparsing=2.1.10=py27_0
- conda-forge::pyqt=4.11.4=py27_0
- conda-forge::python-dateutil=2.5.3=py27_0
- conda-forge::pytz=2016.7=py27_0
- conda-forge::qt=4.8.7=3
- conda-forge::scipy=0.18.1=np111py27_blas_openblas_200
- conda-forge::singledispatch=3.4.0.3=py27_0
- conda-forge::sip=4.18=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::uncertainties=2.4.8.1=py27_1
- conda-forge::xz=5.2.2=0
- iminuit=1.1.1=py27_0
- libgfortran=3.0.0=1
- llvmlite=0.14.0=py27_0
- numba=0.29.0=np111py27_0
- openssl=1.0.2j=0
- pip=8.1.2=py27_0
- pymc=2.3.6=np111py27_2
- python=2.7.12=1
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - cloudpickle==0.2.1
  - cycler==0.10.0
  - enum34==1.1.6
  - funcsigs==1.0.2
  - functools32==3.2.3.post2
  - matplotlib==1.5.3
  - numpy==1.11.2
  - pandas==0.19.0
  - pyparsing==2.1.10
  - python-dateutil==2.5.3
  - pytz==2016.7
  - scipy==0.18.1
  - singledispatch==3.4.0.3
  - six==1.10.0
  - uncertainties==2.4.8.1
